development:
  adapter: postgresql
  encoding: unicode
  database: ECV2_development
  pool: 5
  username: JackMallers
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: ECV2_test
  pool: 5
  username: JackMallers
  password:
